spring.application.name=RagApplication
spring.ai.ollama.base-url=http://xxxx.xxxx.xxxx.xxxx
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Custom property for vector store storage
app.vectorstore.path=vectorstore.json
